theme: minima
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

plugins:
  - jekyll-pdf-embed
 
 minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    linkedin:  https://www.linkedin.com/in/melissafloresdata/
