 minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    linkedin:  melissafloresdata
    
# Build settings
url: "http://mflores.github.io/melissa-flores/"
baseurl: "/melissa-flores"
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-pdf-embed
 - jekyll-responsive-image
 
 responsive_image:
  template: _includes/srcset-resized-fallback.html
  sizes:
    - width: 320
    - width: 480
    - width: 800

permalink: /_pages/:slug
