 minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    linkedin:  melissafloresdata
    
# Build settings
url: "https://melissa-flores.github.io"
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-pdf-embed

permalink: /:categories/:title:output_ext
